services:

  ruby:
    image: tugboatqa/debian
    default: true
    depends: database
    commands:
      init:
        - apt-get update
        - apt-get install ruby ruby-dev
        - apt-get install postgresql-client imagemagick zlib1g-dev libpq-dev libmagickwand-dev
        - gem update --system
        - gem install bundler:1.16.6
        - gem install rake:12.3.1
        - bundle install
        - apt-get clean
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

      update:
        - bin/rails db:setup

      start:
        - bin/rails s -b 0.0.0.0 -p 80

  database:
    image: tugboatqa/postgres:10.13
    commands:
      init:
        - psql -U postgres -d tugboat -c "ALTER USER tugboat WITH CREATEDB;"
      online:
        - psql -U postgres -d tugboat -c "ALTER USER tugboat WITH NOCREATEDB;"
